server:
  host: ${SERVER_HOST}
  port: ${SPRING_PORT}

spring:
  profiles:
    active:
      - local
    group:
      local:
        - local
      prod:
        - prod
    include:
      - db
      - swagger
      - thymeleaf
