# Default 설정
spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

--- # Local 설정
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /1stprojecttest
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/1stprojecttest
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: H2
    hibernate.ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

--- # Prod 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_ROOT_NAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
