spring:
  h2:
    console:
      enabled: true
      path: /1stprojecttest # 콘솔의 경로
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:tcp://localhost/~/1stprojecttest
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /api-docs
