INSERT INTO LECTURE
(LECTURE_YEAR, DEPARTMENT, GRADE, SEMESTER, TYPE, CODE, NAME, CREDIT, REQUIRED, DESIGN)
VALUES
    -- 2019 computer
    (2019, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0263', '문화 기술 개론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0210', '대화형 프로그래밍기초', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0264', '소셜네트워크', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0211', '수학 I', 'THREE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0213', '물리학 I', 'THREE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0223', '물리학실험 I', 'ONE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'SECOND', 'MAJOR_BASE', 'COME0301', '이산수학', 'THREE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0201', '컴퓨터학개론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0205', '기초창의공학설계', 'THREE', TRUE, TRUE),
    (2019, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0209', '소프트웨어와 문제해결', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0689', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0417', '컴퓨터윤리', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'BASIC_KNOWLEDGE', 'COMP0329', 'SW융합커뮤니케이션', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'CLTR0246', '일반생명과학Ⅰ', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'ENGR0211', '공학수학 1', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'MTED0231', '선형대수', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COME0331', '자료구조', 'THREE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'ELEC0462', '시스템프로그래밍', 'THREE', TRUE, TRUE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', TRUE, TRUE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, TRUE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'ELEC0247', '논리회로', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0225', '디지털설계및실험', 'THREE', FALSE, TRUE),
    (2019, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0315', '오토마타및형식언어', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0423', '자료구조프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0086', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0763', '창의적 창업모델개발', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0208', '심화글쓰기', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'BASIC_KNOWLEDGE', 'COMP0330', 'SW프로젝트관리기법', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'MAJOR_BASE', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'MAJOR_BASE', 'STAT0452', '수치해석', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0320', '알고리즘2', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0422', '소프트웨어공학', 'THREE', FALSE, TRUE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0319', '알고리즘1', 'THREE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0323', '데이타통신', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0312', '운영체제', 'THREE', TRUE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'EECS0312', '네트워크프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0401', '종합설계프로젝트1', 'FOUR', TRUE, TRUE),
    (2019, '심화컴퓨터공학', 'THIRD', 'FIRST', 'TEACHER', 'TCHR0499', '컴퓨터 논리 및 논술지도', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0593', '컴퓨터교육론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0594', '컴퓨터교재연구및지도법', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0045', '논리와 비판적 사고', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0424', '무선네트워크', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0414', '컴퓨터망', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0432', '소프트웨어 특강', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0419', '정보검색', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0435', '디지털미디어아트', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0402', '종합설계프로젝트2', 'FOUR', TRUE, TRUE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0421', '소프트웨어디자인패턴', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0413', '인간과컴퓨터상호작용설계', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0417', '기계학습개론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0414', '소프트웨어테스팅이론', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0422', '의료융합소프트웨어', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0420', '모바일로봇프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0520', '생활지도및상담(교직소양)', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0528', '특수교육학개론', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0529', '교직실무', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0552', '교육봉사활동 2', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0601', '교육과정', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0604', '교육방법및교육공학', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0606', '교육사회', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0607', '교육심리', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0609', '교육철학및교육사', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0610', '교육평가', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0611', '교육학개론', 'TWO', FALSE, FALSE),
    (2019, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0612', '교육행정및교육경영', 'TWO', FALSE, FALSE),

    -- 2020 computer
    (2020, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0263', '문화 기술 개론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0210', '대화형 프로그래밍기초', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0264', '소셜네트워크', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0211', '수학 I', 'THREE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0213', '물리학 I', 'THREE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0223', '물리학실험 I', 'ONE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'SECOND', 'MAJOR_BASE', 'COME0301', '이산수학', 'THREE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0209', '소프트웨어와 문제해결', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0201', '컴퓨터학개론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0205', '기초창의공학설계', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0689', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0329', 'SW융합커뮤니케이션', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0417', '컴퓨터윤리', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'CLTR0246', '일반생명과학Ⅰ', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'ENGR0211', '공학수학 1', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'MTED0231', '선형대수', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COME0331', '자료구조', 'THREE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, TRUE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0225', '디지털설계및실험', 'THREE', FALSE, TRUE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', TRUE, TRUE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0315', '오토마타및형식언어', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0432', '소프트웨어 특강', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'ELEC0247', '논리회로', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'ELEC0462', '시스템프로그래밍', 'THREE', TRUE, TRUE),
    (2020, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0423', '자료구조프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0086', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0330', 'SW프로젝트관리기법', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0208', '심화글쓰기', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'MAJOR_BASE', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'MAJOR_BASE', 'STAT0452', '수치해석', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0312', '운영체제', 'THREE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0320', '알고리즘2', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0319', '알고리즘1', 'THREE', TRUE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0323', '데이타통신', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0422', '소프트웨어공학', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'EECS0312', '네트워크프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0401', '종합설계프로젝트1', 'FOUR', TRUE, TRUE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0045', '논리와 비판적 사고', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0424', '무선네트워크', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0414', '컴퓨터망', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'GLSO0229', 'SW창업프로젝트', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0419', '정보검색', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0421', '소프트웨어디자인패턴', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0402', '종합설계프로젝트2', 'FOUR', TRUE, TRUE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0414', '소프트웨어테스팅이론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0435', '디지털미디어아트', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0417', '기계학습개론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0422', '의료융합소프트웨어', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0420', '모바일로봇프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0413', '인간과컴퓨터상호작용설계', 'THREE', FALSE, FALSE),
--     (2020,	'심화컴퓨터공학',	'THIRD',	'SECOND',	type,	'CLTR0763',	'창의적 창업모델개발',	'THREE',	FALSE,	FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0593', '컴퓨터교육론', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0594', '컴퓨터교재연구및지도법', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'THIRD', 'FIRST', 'TEACHER', 'TCHR0499', '컴퓨터 논리 및 논술지도', 'THREE', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'TEACHER', 'TCHR0522', '학교현장실습', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0520', '생활지도및상담(교직소양)', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0528', '특수교육학개론', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0529', '교직실무', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0552', '교육봉사활동 2', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0601', '교육과정', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0604', '교육방법및교육공학', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0606', '교육사회', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0607', '교육심리', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0609', '교육철학및교육사', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0610', '교육평가', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0611', '교육학개론', 'TWO', FALSE, FALSE),
    (2020, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0612', '교육행정및교육경영', 'TWO', FALSE, FALSE),

    -- 2021 computer
    (2021, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0263', '문화 기술 개론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0210', '대화형 프로그래밍기초', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0264', '소셜네트워크', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0211', '수학 I', 'THREE', TRUE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0213', '물리학 I', 'THREE', TRUE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0223', '물리학실험 I', 'ONE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'SECOND', 'MAJOR_BASE', 'COME0301', '이산수학', 'THREE', TRUE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0209', '소프트웨어와 문제해결', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0201', '컴퓨터학개론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0205', '기초창의공학설계', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0689', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0329', 'SW융합커뮤니케이션', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0417', '컴퓨터윤리', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'CLTR0246', '일반생명과학Ⅰ', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'ENGR0211', '공학수학 1', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'MTED0231', '선형대수', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COME0331', '자료구조', 'THREE', TRUE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, TRUE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0225', '디지털설계및실험', 'THREE', FALSE, TRUE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', TRUE, TRUE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', TRUE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0315', '오토마타및형식언어', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0432', '소프트웨어 특강', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'ELEC0247', '논리회로', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'ELEC0462', '시스템프로그래밍', 'THREE', TRUE, TRUE),
    (2021, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0423', '자료구조프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0086', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0330', 'SW프로젝트관리기법', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0208', '심화글쓰기', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'MAJOR_BASE', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'MAJOR_BASE', 'STAT0452', '수치해석', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0312', '운영체제', 'THREE', TRUE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0320', '알고리즘2', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0319', '알고리즘1', 'THREE', TRUE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0323', '데이타통신', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0422', '소프트웨어공학', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'EECS0312', '네트워크프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0401', '종합설계프로젝트1', 'FOUR', TRUE, TRUE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0045', '논리와 비판적 사고', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0424', '무선네트워크', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0414', '컴퓨터망', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'GLSO0229', 'SW창업프로젝트', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0419', '정보검색', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0421', '소프트웨어디자인패턴', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0402', '종합설계프로젝트2', 'FOUR', TRUE, TRUE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0414', '소프트웨어테스팅이론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0435', '디지털미디어아트', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0417', '기계학습개론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0422', '의료융합소프트웨어', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0420', '모바일로봇프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0413', '인간과컴퓨터상호작용설계', 'THREE', FALSE, FALSE),
--     (2021,  '심화컴퓨터공학',	'THIRD',	'SECOND',	type,	'CLTR0763',	'창의적 창업모델개발',	'THREE',	FALSE,	FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0593', '컴퓨터교육론', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0594', '컴퓨터교재연구및지도법', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'THIRD', 'FIRST', 'TEACHER', 'TCHR0499', '컴퓨터 논리 및 논술지도', 'THREE', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'TEACHER', 'TCHR0522', '학교현장실습', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0520', '생활지도및상담(교직소양)', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0528', '특수교육학개론', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0529', '교직실무', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0552', '교육봉사활동 2', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0601', '교육과정', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0604', '교육방법및교육공학', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0606', '교육사회', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0607', '교육심리', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0609', '교육철학및교육사', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0610', '교육평가', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0611', '교육학개론', 'TWO', FALSE, FALSE),
    (2021, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0612', '교육행정및교육경영', 'TWO', FALSE, FALSE),

    -- 2022 computer
    (2022, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0045', '논리와 비판적 사고', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'FIRST', 'BASIC_KNOWLEDGE', 'CLTR0264', '소셜네트워크', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0211', '수학 I', 'THREE', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0213', '물리학 I', 'THREE', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'FIRST', 'MAJOR_BASE', 'CLTR0223', '물리학실험 I', 'ONE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'SECOND', 'MAJOR_BASE', 'COME0301', '이산수학', 'THREE', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0453', '컴퓨팅사고와 SW코딩', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0201', '컴퓨터학개론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FIRST', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0205', '기초창의공학설계', 'THREE', TRUE, TRUE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'FUTR0208', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'CLTR0246', '일반생명과학Ⅰ', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'MAJOR_BASE', 'COMP0454', '인공지능수학기초', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'MAJOR_BASE', 'MTED0231', '선형대수', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', TRUE, TRUE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, TRUE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0315', '오토마타및형식언어', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0225', '디지털설계및실험', 'THREE', FALSE, TRUE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'ELEC0247', '논리회로', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COME0331', '자료구조', 'THREE', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0432', '소프트웨어 특강', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'SECOND', 'SECOND', 'ENGINEERING_MAJOR', 'ELEC0462', '시스템프로그래밍', 'THREE', TRUE, TRUE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'BASIC_KNOWLEDGE', 'FUTR0201', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'BASIC_KNOWLEDGE', 'FUTR0214', '창업과 경영', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'MAJOR_BASE', 'STAT0452', '수치해석', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'TEACHER', 'TCHR0499', '컴퓨터 논리 및 논술지도', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0593', '컴퓨터교육론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'TEACHER', 'TCHR0594', '컴퓨터교재연구및지도법', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0312', '운영체제', 'THREE', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0320', '알고리즘2', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0319', '알고리즘1', 'THREE', TRUE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0323', '데이타통신', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'EECS0312', '네트워크프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0422', '소프트웨어공학', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0417', '기계학습개론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'THIRD', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0401', '종합설계프로젝트1', 'FOUR', TRUE, TRUE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'BASIC_KNOWLEDGE', 'COMP0417', '컴퓨터윤리', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'BASIC_KNOWLEDGE', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'CAIB0211', '자연어처리개론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0414', '컴퓨터망', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0419', '정보검색', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0435', '디지털미디어아트', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0436', '증강현실', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0462', '데이터마이닝이론및응용', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0455', '지능HCI', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'COMP0460', '문제해결기반 공학연수실습(컴퓨터학)', 'THREE', FALSE,
     FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0457', '의료인공지능', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'GLSO0215', '오픈소스프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0458', '모바일네트워크', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'GLSO0224', '사물인터넷', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'COMP0461', '문제해결기반 공학연수실습(심화컴퓨터학)', 'THREE', FALSE,
     FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0402', '종합설계프로젝트2', 'FOUR', TRUE, TRUE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'GLSO0227', '클라우드컴퓨팅', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0414', '소프트웨어테스팅이론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'GLSO0229', 'SW창업프로젝트', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'MBIO0402', '생물정보학개론', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'ENGINEERING_MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'ENGINEERING_MAJOR', 'MOBI0224', '딥러닝', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'FIRST', 'TEACHER', 'TCHR0522', '학교현장실습', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'FOURTH', 'SECOND', 'TEACHER', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0520', '생활지도및상담(교직소양)', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0528', '특수교육학개론', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0529', '교직실무', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0552', '교육봉사활동 2', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0601', '교육과정', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0604', '교육방법및교육공학', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0606', '교육사회', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0607', '교육심리', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0609', '교육철학및교육사', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0610', '교육평가', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0611', '교육학개론', 'TWO', FALSE, FALSE),
    (2022, '심화컴퓨터공학', 'ALL', 'FIRST', 'TEACHER', 'TCHR0612', '교육행정및교육경영', 'TWO', FALSE, FALSE),

    -- 2019 global
    (2019, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0211', '수학 I', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0266', 'SW 사고기법', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COME0301', '이산수학', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COME0331', '자료구조', 'THREE', TRUE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', TRUE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'GLSO0212', '소프트웨어수학', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'GLSO0211', 'SW실용영어', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'GLSO0213', '창의융합설계', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'CLTR0086', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'SECOND', 'LIBERAL', 'STUP0212', '창업과 경영', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'CLTR0689', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'SECOND', 'LIBERAL', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0312', '운영체제', 'THREE', TRUE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0214', 'SW진로설계', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0215', '오픈소스프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'GLSO0217', '컴퓨터망프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0216', '알고리즘실습', 'THREE', TRUE, FALSE),
    (2019, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'FIRST', 'LIBERAL', 'CLTR0208', '심화글쓰기', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'SECOND', 'LIBERAL', 'CLTR0089', '회계와사회생활', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'FIRST', 'LIBERAL', 'STUP0224', '나의 첫 사업제안서', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'SECOND', 'LIBERAL', 'STUP0217', '글로벌창업실습개론', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0218', 'SW융합설계1', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0219', 'SW공학및테스팅', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'GLSO0231', 'SW융합설계2', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0220', '소프트웨어융합특강1', 'ONE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'GLSO0222', '소프트웨어융합특강2', 'ONE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'LIBERAL', 'CLTR0761', '창조성개발과 혁신창업', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'LIBERAL', 'CLTR0790', '알기쉬운창업마케팅', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0223', '스타트업설계', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0229', 'SW창업프로젝트', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0224', '사물인터넷', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0227', '클라우드컴퓨팅', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0225', '소프트웨어융합특강3', 'ONE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0228', '소프트웨어융합특강4', 'ONE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0413', '인간과 컴퓨터 상호작용 설계', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0421', '소프트웨어디자인패턴', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0420', '모바일로봇프로그래밍', 'THREE', FALSE, FALSE),
    (2019, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0211', '수학 I', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0266', 'SW 사고기법', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COME0301', '이산수학', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COME0331', '자료구조', 'THREE', TRUE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', TRUE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'GLSO0211', 'SW실용영어', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'GLSO0212', '소프트웨어수학', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'GLSO0213', '창의융합설계', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'CLTR0086', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'SECOND', 'LIBERAL', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'CLTR0689', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'SECOND', 'NORMAL', 'STUP0212', '창업과 경영', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0312', '운영체제', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0214', 'SW진로설계', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0215', '오픈소스프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'GLSO0217', '컴퓨터망프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0216', '알고리즘실습', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'FIRST', 'LIBERAL', 'CLTR0208', '심화글쓰기', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'SECOND', 'LIBERAL', 'CLTR0089', '회계와사회생활', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'FIRST', 'NORMAL', 'CLTR0779', '나의 첫 사업제안서', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'SECOND', 'NORMAL', 'CLTR0757', '글로벌창업실습개론', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0230', 'SW융합설계1(캡스톤디자인)', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0219', 'SW공학및테스팅', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'GLSO0231', 'SW융합설계2(캡스톤디자인)', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0220', '소프트웨어융합특강1', 'ONE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'GLSO0222', '소프트웨어융합특강2', 'ONE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'NORMAL', 'FUTR0219', '창조성개발과 혁신창업', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'NORMAL', 'FUTR0231', '알기쉬운 창업마케팅과 스피치', 'THREE', FALSE, FALSE),

    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0223', '스타트업설계', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0227', '클라우드컴퓨팅', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0224', '사물인터넷', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0228', '소프트웨어융합특강4', 'ONE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0225', '소프트웨어융합특강3', 'ONE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0229', 'SW창업프로젝트', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0413', '인간과 컴퓨터 상호작용 설계', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0421', '소프트웨어디자인패턴', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE),
    (2020, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0420', '모바일로봇프로그래밍', 'THREE', FALSE, FALSE),
--     (2020,	'글로벌SW융합전공',	'FOURTH',	'FIRST',	type,	'COMP0461',	'문제해결기반 공학연수실습(심화컴퓨터학)',	'TWO',	FALSE,	FALSE),
--     (2020,	'글로벌SW융합전공',	'FOURTH',	'SECOND',	type,	'COMP0457',	'의료인공지능',	'THREE',	FALSE,	FALSE),
--     (2020,	'글로벌SW융합전공',	'FOURTH',	'FIRST',	type,	'MOBI0224',	'딥러닝',	'THREE',	FALSE,	FALSE),

    -- 2021 global
    (2021, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0211', '수학 I', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0266', 'SW 사고기법', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COME0301', '이산수학', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COME0331', '자료구조', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'GLSO0211', 'SW실용영어', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'GLSO0212', '소프트웨어수학', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'GLSO0213', '창의융합설계', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'CLTR0086', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'SECOND', 'LIBERAL', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'CLTR0689', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'SECOND', 'NORMAL', 'CLTR0732', '창업과 경영', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0312', '운영체제', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0214', 'SW진로설계', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0215', '오픈소스프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'GLSO0217', '컴퓨터망프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0216', '알고리즘실습', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'FIRST', 'LIBERAL', 'CLTR0208', '심화글쓰기', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'SECOND', 'LIBERAL', 'CLTR0089', '회계와사회생활', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'FIRST', 'NORMAL', 'FUTR0226', '나의 첫 사업제안서', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'SECOND', 'NORMAL', 'FUTR0218', '글로벌창업실습개론', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0230', 'SW융합설계1(캡스톤디자인)', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0219', 'SW공학및테스팅', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'GLSO0231', 'SW융합설계2(캡스톤디자인)', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0220', '소프트웨어융합특강1', 'ONE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'GLSO0222', '소프트웨어융합특강2', 'ONE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'NORMAL', 'FUTR0219', '창조성개발과 혁신창업', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'NORMAL', 'FUTR0231', '알기쉬운 창업마케팅과 스피치', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0223', '스타트업설계', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0227', '클라우드컴퓨팅', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0224', '사물인터넷', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0228', '소프트웨어융합특강4', 'ONE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0225', '소프트웨어융합특강3', 'ONE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0229', 'SW창업프로젝트', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0413', '인간과 컴퓨터 상호작용 설계', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0421', '소프트웨어디자인패턴', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE),
    (2021, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0420', '모바일로봇프로그래밍', 'THREE', FALSE, FALSE),

    -- 2022 global
    (2022, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0211', '수학 I', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0003', '실용화법', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'FIRST', 'LIBERAL', 'CLTR0266', 'SW 사고기법', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'SECOND', 'LIBERAL', 'CLTR0205', '대학글쓰기', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COMP0204', '프로그래밍기초', 'SIX', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COME0331', '자료구조', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'COME0301', '이산수학', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COMP0216', '자료구조응용', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'FIRST', 'MAJOR', 'ITEC0201', '컴퓨터학개론', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'COMP0453', '컴퓨팅사고와 SW코딩', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FIRST', 'SECOND', 'MAJOR', 'GLSO0213', '창의융합설계', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'FUTR0201', '기업가정신과 벤처창업', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'SECOND', 'LIBERAL', 'CLTR0043', '서양의역사와문화', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'LIBERAL', 'FUTR0208', '미래산업과 직업선택', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'SECOND', 'LIBERAL', 'FUTR0214', '창업과 경영', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0216', '알고리즘실습', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0312', '운영체제', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COME0311', '확률및통계', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0224', '소프트웨어설계', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COMP0217', '자바프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0323', '데이타통신', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'COMP0411', '컴퓨터구조', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'COMP0324', '인공지능', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'ELEC0462', '시스템프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'SECOND', 'MAJOR', 'GLSO0212', '소프트웨어수학', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'SECOND', 'FIRST', 'MAJOR', 'GLSO0214', 'SW진로설계', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'FIRST', 'LIBERAL', 'FUTR0226', '나의 첫 사업제안서', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'SECOND', 'LIBERAL', 'CLTR0089', '회계와사회생활', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'COMP0432', '소프트웨어 특강', 'TWO', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'COMP0322', '데이타베이스', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'EECS0312', '네트워크프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'COMP0328', '모바일앱프로그래밍1', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'GLSO0219', 'SW공학및테스팅', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'COMP0414', '컴퓨터망', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'ITEC0415', '고급문제해결', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'COMP0460', '문제해결기반 공학연수실습(컴퓨터학)', 'TWO', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'FIRST', 'MAJOR', 'ITEC0419', '데이터과학기초', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'THIRD', 'SECOND', 'MAJOR', 'ITEC0417', '기계학습개론', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'LIBERAL', 'FUTR0219', '창조성개발과 혁신창업', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'LIBERAL', 'FUTR0231', '알기쉬운 창업마케팅과 스피치', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0321', '컴파일러', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'CAIB0211', '자연어처리개론', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0413', '컴퓨터그래픽스', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COME0368', '정보보호론', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0420', '모바일앱프로그래밍2', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0423', '프로그래밍언어론', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0462', '데이터마이닝이론및응용', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0428', 'IT기술경영개론', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'COMP0461', '문제해결기반 공학연수실습(심화컴퓨터학)', 'TWO', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0436', '증강현실', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0215', '오픈소스프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0455', '지능HCI', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0223', '스타트업설계', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'COMP0457', '의료인공지능', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'GLSO0224', '사물인터넷', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0227', '클라우드컴퓨팅', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0401', '종합설계프로젝트1', 'FOUR', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'GLSO0229', 'SW창업프로젝트', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0403', 'IT지식재산권', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0402', '종합설계프로젝트2', 'FOUR', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'ITEC0416', '고급웹프로그래밍', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0418', '대규모병렬컴퓨팅', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'MBIO0402', '생물정보학개론', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0424', '컴퓨터비전', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'FIRST', 'MAJOR', 'MOBI0224', '딥러닝', 'THREE', FALSE, FALSE),
    (2022, '글로벌SW융합전공', 'FOURTH', 'SECOND', 'MAJOR', 'ITEC0425', '컴퓨터게임제작', 'THREE', FALSE, FALSE)
;
